name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

env:
  NODE_VERSION: lts/*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up PNPM
        uses: pnpm/action-setup@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install

      - name: Lint with ESLint
        run: pnpm eslintCheck

      - name: Typecheck with tsc
        run: pnpm typeCheck

      - name: Format with prettier
        run: pnpm prettierCheck
